[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
manejador_loterias = "GVEW7KHyM4knGLYQXyME1gzAxvtDGP9oPoVcppXYoNwH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sektersyto/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
